{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"summer\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "summer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "summer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "straw-hat": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "temporary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "travelling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "traveling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "summertime": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "solstice": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "midsummer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "season": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "summer.athlete": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Athlete"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "athlete": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sportsperson": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "contestant": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "competitor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "player": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "participant": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "summer.city": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "City"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "city": {
                      "State": "Generated"
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "metropolis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "municipality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "town": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "metropolitan": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "summer.country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "summer.discipline": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Discipline"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "discipline": {
                      "State": "Generated"
                    }
                  },
                  {
                    "punishment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "correction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "chastisement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "castigation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "restraint": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "regulation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "strictness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "mastery": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "continence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "self-control": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "summer.event": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Event"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "event": {
                      "State": "Generated"
                    }
                  },
                  {
                    "occurrence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "affair": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "episode": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "occasion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "happening": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "incident": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "experience": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "aftermath": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "upshot": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "summer.gender": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Gender"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "gender": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sexuality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "sex": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "summer.medal": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Medal"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medal": {
                      "State": "Generated"
                    }
                  },
                  {
                    "memento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "distinction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "kudos": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "accolade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "decoration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "honor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "souvenir": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "laurel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "summer.sport": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Sport"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sport": {
                      "State": "Generated"
                    }
                  },
                  {
                    "diversion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "amusement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "hobby": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "pastime": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "entertainment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "game": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "activity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "summer.total_medals": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "TotalMedals"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total medals": {
                      "State": "Generated"
                    }
                  },
                  {
                    "medals": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate medal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall medal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total memento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total distinction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total accolade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "memento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "distinction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "accolade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "total award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total decoration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "Gold Medals Won": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Silver Medals Won": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Bronze Medals Won": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "summer.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "summer",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "summer_has_athlete": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.athlete"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_athletes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.athlete": {
                    "Target": {
                      "Entity": "summer.athlete"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_city": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.city"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_cities",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.city": {
                    "Target": {
                      "Entity": "summer.city"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_country": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.country"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.country": {
                    "Target": {
                      "Entity": "summer.country"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_discipline": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.discipline"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_disciplines",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.discipline": {
                    "Target": {
                      "Entity": "summer.discipline"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_event": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.event"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_events",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.event": {
                    "Target": {
                      "Entity": "summer.event"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_gender": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.gender"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_genders",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.gender": {
                    "Target": {
                      "Entity": "summer.gender"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_medal": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.medal"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_medals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.medal": {
                    "Target": {
                      "Entity": "summer.medal"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_sport": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.sport"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_sports",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.sport": {
                    "Target": {
                      "Entity": "summer.sport"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_total_medals": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.total_medals"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_total_medals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.total_medals": {
                    "Target": {
                      "Entity": "summer.total_medals"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_has_year": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "summer.year"
                      },
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "ID": "summers_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.year": {
                    "Target": {
                      "Entity": "summer.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "summer_in_city": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "ID": "summers_are_in_cities",
                    "Preposition": {
                      "Object": {
                        "Role": "summer.city"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.city": {
                    "Target": {
                      "Entity": "summer.city"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "summer.city"
                  }
                },
                "State": "Generated"
              },
              "summer_in_country": {
                "Binding": {
                  "ConceptualEntity": "summer"
                },
                "Phrasings": [
                  {
                    "ID": "summers_are_in_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "summer.country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "summer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "summer": {
                    "Target": {
                      "Entity": "summer"
                    }
                  },
                  "summer.country": {
                    "Target": {
                      "Entity": "summer.country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "summer.country"
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-NG",
    "tables": [
      {
        "name": "summer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ba54f02-5276-4867-b4ac-f1c0ffc88948",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3620aef2-9997-4b31-86a8-38912a469065",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Sport",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdfd747b-04c1-4de9-bc55-d0857761ba92",
            "sourceColumn": "Sport",
            "summarizeBy": "none"
          },
          {
            "name": "Discipline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a82559d0-312e-4b3d-ae4d-38b2ed3c92a2",
            "sourceColumn": "Discipline",
            "summarizeBy": "none"
          },
          {
            "name": "Athlete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cfd8eb3-1838-4363-a1ad-c4fae3e6a86b",
            "sourceColumn": "Athlete",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "170a9c69-ec59-433c-a625-a29e2b907b58",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5da476f-ad44-407e-93df-af9515411bbc",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7443b22f-803c-444c-8f0c-6eb650e6ec73",
            "sourceColumn": "Event",
            "summarizeBy": "none"
          },
          {
            "name": "Medal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ce50828-2d27-465c-887a-6f6bfcc86508",
            "sourceColumn": "Medal",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cca83ed7-cb4f-4233-8a82-8461086783bb",
        "measures": [
          {
            "name": "TotalMedals",
            "expression": "COUNT(summer[Medal])",
            "formatString": "#,0",
            "lineageTag": "754f813c-a56f-4a0f-910d-5189c117f489"
          }
        ],
        "partitions": [
          {
            "name": "summer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Olawale Ahmed\\Desktop\\POWER BI RESOURCES\\summer.csv\"),[Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"City\", type text}, {\"Sport\", type text}, {\"Discipline\", type text}, {\"Athlete\", type text}, {\"Country\", type text}, {\"Gender\", type text}, {\"Event\", type text}, {\"Medal\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Filtered Rows\",{{\"City\", Text.Proper, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Capitalized Each Word\",{{\"City\", Text.Trim, type text}}),",
                "    #\"Capitalized Each Word1\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Sport\", Text.Proper, type text}}),",
                "    #\"Trimmed Text1\" = Table.TransformColumns(#\"Capitalized Each Word1\",{{\"Sport\", Text.Trim, type text}}),",
                "    #\"Capitalized Each Word2\" = Table.TransformColumns(#\"Trimmed Text1\",{{\"Discipline\", Text.Proper, type text}}),",
                "    #\"Trimmed Text2\" = Table.TransformColumns(#\"Capitalized Each Word2\",{{\"Discipline\", Text.Trim, type text}}),",
                "    #\"Capitalized Each Word3\" = Table.TransformColumns(#\"Trimmed Text2\",{{\"Athlete\", Text.Proper, type text}}),",
                "    #\"Trimmed Text3\" = Table.TransformColumns(#\"Capitalized Each Word3\",{{\"Athlete\", Text.Trim, type text}, {\"Country\", Text.Trim, type text}}),",
                "    #\"Capitalized Each Word4\" = Table.TransformColumns(#\"Trimmed Text3\",{{\"Gender\", Text.Proper, type text}}),",
                "    #\"Trimmed Text4\" = Table.TransformColumns(#\"Capitalized Each Word4\",{{\"Gender\", Text.Trim, type text}, {\"Event\", Text.Trim, type text}}),",
                "    #\"Capitalized Each Word5\" = Table.TransformColumns(#\"Trimmed Text4\",{{\"Event\", Text.Proper, type text}, {\"Medal\", Text.Proper, type text}}),",
                "    #\"Trimmed Text5\" = Table.TransformColumns(#\"Capitalized Each Word5\",{{\"Medal\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text5\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}